### ISSUE TITLE
Features TODO

### ISSUE THREAD

**Issue by HermesPasser** [HermesPasser/comic-pub#1]
- [x] create epub structure
- [x] get input file images
  - [x] uncompress if is a zip
- [x] process the images if need
  - [ ] stretch/warn if they too small for the device (we need to store the size of some devices if so)
      * should we use css to do that or edit the img itself?
  - [x] split in two if too big for the device (kcc does it)
      * test with letting the page be in landscape mode too
   - [x] **reduce the image size** _[1]_
      * can be done by reducing the quality (we don't need high res on small devices and it can be done in a way that is not that apparent)
      * resize down to the device's size?
- [ ] add to epub any metadata from cbz
- [x] add the images to epub
  - [x] move the images to image folder
  - [x] create xhtml to them 
  - [x] put images and xhtmls in manifest 
  - [x] put images in toc/nav and in any other place they need to be declared
      - [x] if the original zip/folder has sub-folders with the images then make each sub-folder as a chapter in the epub
      - [ ] make the toc (not as a rendition but a toc to select the chapters) since as right now there is no way to select the chapter w/o going to the last page on epubs made with the ``--toc`` flag set
- [x] write comic unrelated metadata i.e. ``uid`` and ``datechanged``
- [x] zip folder as epub

_[1]: official released comics are way heavier than you everyday scanlation so this feature is very important._
